
export const  FETCH_HIGHLIGHTS = "HIGHLIGHTS/FETCH_HIGHLIGHTS"
export const  FETCH_HIGHLIGHTS_SUCCESS = "HIGHLIGHTS/FETCH_HIGHLIGHTS_SUCCESS"
export const  SET_HIGHLIGHTS_PAYLOAD = "HIGHLIGHTS/SET_HIGHLIGHTS_PAYLOAD"
export const  FETCH_PROMOTIONS = "PROMOTIONS/FETCH_PROMOTIONS"
export const  FETCH_PROMOTIONS_SUCCESS = "PROMOTIONS/FETCH_PROMOTIONS_SUCCESS"
export const  SET_PROMOTIONS_PAYLOAD = "PROMOTIONS/SET_PROMOTIONS_PAYLOAD"

