export const FETCH_API_DATA = "REST_API_SAGA/FETCH_API_DATA";
export const ON_FETCH_ERROR = "REST_API_SAGA/ON_FETCH_ERROR";
export const ON_LOGIN_REQUEST = "AUTH_SAGA/ON_LOGIN_REQUEST";
export const ON_LOGIN_REQUEST_FAILURE = "AUTH_SAGA/ON_LOGIN_REQUEST_FAILURE";
export const ON_LOGIN_REQUEST_SUCCESS = "AUTH_SAGA/ON_LOGIN_REQUEST_SUCCESS";
export const ON_LOGIN_USER_REJECTION = "AUTH_SAGA/ON_LOGIN_USER_REJECTION";